name: Autograding

on: [push, pull_request]

jobs:
  run-autograding-r-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2'
        use-public-rspm: true

    - name: Install Packages
      run: |
        Rscript -e 'install.packages("testthat"); install.packages("here")'


    - name: ExampleTests
      id: exampletests
      uses: classroom-resources/autograding-command-grader@v1
      with: 
          test-name: ExampleTests
          command: Rscript -e 'testthat::test_dir("tests", reporter="summary")'
          timeout: 10
          max-score: 100

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EXAMPLETESTS_RESULTS: ${{ steps.exampletests.outputs.result }}
      with:
        runners: exampletests