name: Autograding

on: [push, pull_request]

jobs:
  autograding:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2'

    - name: Install Dependencies
      run: |
          Rscript -e 'install.packages("testthat")'

    - name: Run Tests
      run: |
        # Run tests and output results in a format GitHub Classroom can read
        Rscript -e 'testthat::test_dir("tests", reporter="summary")'